"""first migrate

Revision ID: fc77d041db20
Revises: 
Create Date: 2026-07-30 11:55:56.146814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc77d041db20'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_classes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recommendation_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('target_need', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.String(length=255), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=True),
    sa.Column('product_valuation', sa.Integer(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('is_positive', sa.Boolean(), nullable=True),
    sa.Column('sentiment_reasoning', sa.Text(), nullable=True),
    sa.Column('problem_class_id', sa.Integer(), nullable=True),
    sa.Column('problem_reasoning', sa.Text(), nullable=True),
    sa.Column('recommended_product_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('need_determined', sa.Text(), nullable=True),
    sa.Column('generated_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['problem_class_id'], ['problem_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_analyses_review_id'), 'review_analyses', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_analyses_review_id'), table_name='review_analyses')
    op.drop_table('review_analyses')
    op.drop_table('recommendation_products')
    op.drop_table('problem_classes')
    # ### end Alembic commands ###
